### ISSUE TITLE
Hardcoded Python path causing issues on RHEL/CentOS 8

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/ranger-old#6]
Some scripts have hardcoded references to the `python` command. This command is normally replaced by the `PYTHON_COMMAND_INVOKER` environment variable.

This causes issues on environment where the `python` command does not exist, like RHEL/CentOS 8 (see [What, no Python in Red Hat Enterprise Linux 8?](https://developers.redhat.com/blog/2019/05/07/what-no-python-in-red-hat-enterprise-linux-8)).

Scripts impacted:
https://github.com/TOSIT-IO/ranger/blob/9f9d713ba83f251607dc702fbca87e680cabd6bf/security-admin/scripts/setup.sh#L224
https://github.com/TOSIT-IO/ranger/blob/9f9d713ba83f251607dc702fbca87e680cabd6bf/security-admin/scripts/setup.sh#L294
https://github.com/TOSIT-IO/ranger/blob/9f9d713ba83f251607dc702fbca87e680cabd6bf/kms/scripts/setup.sh#L190
https://github.com/TOSIT-IO/ranger/blob/9f9d713ba83f251607dc702fbca87e680cabd6bf/kms/scripts/setup.sh#L301
https://github.com/TOSIT-IO/ranger/blob/9f9d713ba83f251607dc702fbca87e680cabd6bf/unixauthservice/scripts/setup.py#L600
https://github.com/TOSIT-IO/ranger/blob/9f9d713ba83f251607dc702fbca87e680cabd6bf/tagsync/scripts/setup.py#L512

**Comment by leopaul36** [comment]
We could try to backport [RANGER-2759](https://issues.apache.org/jira/browse/RANGER-2759)

**Comment by Nuttymoon** [comment]
> We could try to backport [RANGER-2759](https://issues.apache.org/jira/browse/RANGER-2759)

Not sure this would fix this. The issue is really just a command naming thing. Replacing `python` by `$PYTHON_COMMAND_INVOKER` should do the trick.

**Comment by nschung** [comment]
I'm working on Rocky 8. I forced python to python3 (alternatives --set python /usr/bin/python3) and upgraded Ranger version to 2.2. The RANGER-2759 works on 2.1.

**Comment by Nuttymoon** [comment]
> I'm working on Rocky 8. I forced python to python3 (alternatives --set python /usr/bin/python3) and upgraded Ranger version to 2.2. The RANGER-2759 works on 2.1.

Yes I also got around the issue using `alternatives` but this is still a bug. There is a variable `$PYTHON_COMMAND_INVOKER` that should be used and it isn't. For me we have to edit the scripts to use this variable.

**Comment by nschung** [comment]
A part of this bug, do you have any issue with Ranger installation on RHEL8?

**Comment by Nuttymoon** [comment]
> A part of this bug, do you have any issue with Ranger installation on RHEL8?

No apart from this everything works fine.

**Comment by leopaul36** [comment]
Note that there is still trace of the `python` command on branch `master` of [Apache Ranger](https://github.com/apache/ranger/):

- https://github.com/apache/ranger/blob/master/unixauthservice/scripts/setup.py
- https://github.com/apache/ranger/blob/master/tagsync/scripts/setup.py
